name: taskist
description: Task List App

version: 1.0.0+6

environment:
    sdk: ">=2.12.0 <=3.5.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  font_awesome_flutter: ^10.7.0

  flutter_colorpicker: ^1.1.0
  flutter_slidable: ^3.1.1

  url_launcher: ^6.3.0
  share_plus:  ^10.0.2
  launch_review: ^3.0.1

  modal_progress_hud_nsn: ^0.5.1

  connectivity_plus: ^6.0.5

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/list.png